coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 90%
        threshold: 1%
        only_pulls: true

ignore:
  - '.github/**'
  - '.changeset/**'
  - 'docs/**'
  - 'packages/cli/src/cli.tsx'
  - 'scripts/**'
  - '**/*.md'
  - '**/*.yml'
  - '**/*.yaml'
